<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title','BlueGate')</title><meta name="theme-color" content="#06101d">
<style>
:root{
 --bg:#06101d;--bg2:#091827;--panel:rgba(13,29,48,.86);--panel2:#10243a;--soft:#142b45;
 --line:rgba(137,183,226,.16);--line2:rgba(137,183,226,.28);--text:#f7fbff;--muted:#8fa8c0;
 --blue:#4da6ff;--blue2:#82c5ff;--ok:#49d59c;--warn:#ffc966;--danger:#ff7185;
 --shadow:0 24px 80px rgba(0,0,0,.28);--radius:22px;--radius-sm:14px
}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Tahoma,Arial,sans-serif;background:
radial-gradient(circle at 80% -10%,rgba(44,137,255,.17),transparent 34rem),
radial-gradient(circle at -10% 50%,rgba(31,107,190,.10),transparent 30rem),
linear-gradient(180deg,var(--bg),#081522 55%,#06101d);color:var(--text);min-height:100vh}
a{text-decoration:none;color:inherit}button,input,select,textarea{font:inherit}.container{width:min(1200px,calc(100% - 34px));margin:auto}
.nav{height:76px;display:flex;align-items:center;justify-content:space-between;position:relative;z-index:10}
.brand{font-weight:900;font-size:22px;letter-spacing:.2px;display:flex;align-items:center;gap:10px}.brand-mark{width:34px;height:34px;border-radius:11px;background:linear-gradient(145deg,#73c1ff,#247cff);box-shadow:0 8px 25px rgba(36,124,255,.3);position:relative}.brand-mark:after{content:"";position:absolute;inset:8px;border:2px solid #06111e;border-radius:8px}.brand span{color:var(--blue2)}
.navlinks{display:flex;gap:9px;align-items:center}.btn{border:1px solid var(--line2);background:rgba(15,34,54,.8);color:#fff;padding:11px 16px;border-radius:13px;cursor:pointer;font-weight:800;transition:.18s ease;display:inline-flex;align-items:center;justify-content:center;gap:7px}.btn:hover{transform:translateY(-1px);border-color:rgba(111,183,255,.55);background:#142c46}.btn.primary{background:linear-gradient(135deg,#2788f8,#72beff);color:#04111e;border:0;box-shadow:0 10px 28px rgba(38,137,249,.23)}.btn.ghost{background:transparent}.btn.danger{color:#ffc2ca;border-color:rgba(255,113,133,.25)}
.hero{padding:78px 0 60px;display:grid;grid-template-columns:1.12fr .88fr;gap:46px;align-items:center}.eyebrow{display:inline-flex;padding:8px 12px;border:1px solid rgba(85,167,255,.24);background:rgba(55,145,240,.08);border-radius:999px;color:#8ac8ff;font-weight:900;font-size:12px;letter-spacing:1.3px;margin-bottom:17px}.hero h1{font-size:clamp(42px,6vw,76px);line-height:1.08;margin:0 0 20px;letter-spacing:-2px}.gradient-text{background:linear-gradient(90deg,#fff,#7fc4ff);-webkit-background-clip:text;color:transparent}.hero p{font-size:17px;line-height:2;color:var(--muted);max-width:700px}.hero-actions{display:flex;gap:10px;margin-top:26px;flex-wrap:wrap}
.hero-card,.card{background:linear-gradient(180deg,rgba(17,37,59,.91),rgba(10,25,42,.91));border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);backdrop-filter:blur(15px)}.hero-card{padding:27px;position:relative;overflow:hidden}.hero-card:before{content:"";position:absolute;width:190px;height:190px;border-radius:50%;background:rgba(54,150,255,.12);filter:blur(5px);left:-80px;top:-100px}.metric{display:flex;justify-content:space-between;align-items:center;padding:17px 0;border-bottom:1px solid var(--line);position:relative}.metric:last-child{border-bottom:0}
.section{padding:36px 0}.section h2{font-size:29px;margin:0 0 8px}.section-lead{color:var(--muted);margin:0 0 22px;line-height:1.8}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:17px}.card{padding:22px}.card h3{margin:0 0 9px}.muted{color:var(--muted)}.price{font-size:27px;font-weight:900;margin:17px 0}.pill{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:999px;background:rgba(51,142,235,.11);border:1px solid rgba(82,166,255,.16);color:#8bc9ff;font-size:12px;font-weight:800}.pill.ok{color:#82e8bd;background:rgba(73,213,156,.09);border-color:rgba(73,213,156,.18)}.footer{padding:48px 0;color:var(--muted);text-align:center}
.auth-wrap{min-height:calc(100vh - 76px);display:grid;place-items:center;padding:30px}.auth{width:min(450px,100%);padding:30px}.field{margin:14px 0}.field label{display:block;margin-bottom:8px;color:#c7d6e5;font-size:13px}.input{width:100%;border:1px solid var(--line2);background:rgba(6,17,29,.75);color:#fff;border-radius:13px;padding:13px 14px;outline:none;transition:.18s}.input:focus{border-color:#4da6ff;box-shadow:0 0 0 3px rgba(77,166,255,.09)}textarea.input{resize:vertical}.alert{padding:13px 15px;border-radius:13px;margin:12px 0;background:rgba(145,35,55,.3);border:1px solid rgba(255,113,133,.22);color:#ffc2ca}.success{background:rgba(30,112,77,.25);border-color:rgba(73,213,156,.2);color:#a7f1cf}
.shell{display:grid;grid-template-columns:255px 1fr;min-height:calc(100vh - 76px);gap:22px;padding-bottom:36px}.sidebar{padding:14px;height:max-content;position:sticky;top:18px}.user-chip{padding:12px;margin-bottom:9px;border-bottom:1px solid var(--line)}.user-chip strong{display:block;margin-bottom:4px}.side-section{font-size:10px;color:#607c97;padding:14px 12px 5px;font-weight:900;letter-spacing:1px}.side a{display:flex;align-items:center;gap:10px;padding:11px 12px;border-radius:12px;color:#b6c8da;margin:3px 0;font-size:13px;transition:.15s}.side a:before{content:"";width:7px;height:7px;border-radius:50%;background:#35536f}.side a:hover,.side a.active{background:linear-gradient(90deg,rgba(49,140,235,.18),rgba(49,140,235,.05));color:#fff}.side a.active:before{background:#68b8ff;box-shadow:0 0 12px #4da6ff}.content{min-width:0}.top-title{display:flex;justify-content:space-between;align-items:center;gap:15px;margin:25px 0 17px}.top-title h2{margin:0 0 5px;font-size:27px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.stat{padding:18px;position:relative;overflow:hidden}.stat:after{content:"";position:absolute;width:70px;height:70px;border-radius:50%;background:rgba(74,166,255,.07);left:-20px;top:-25px}.stat b{font-size:25px;display:block;margin-top:8px}.stat small{color:#6f8aa5}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:14px 13px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}.table th{color:#7993ad;font-size:11px;text-transform:uppercase}.table tr:last-child td{border-bottom:0}.table tr:hover td{background:rgba(255,255,255,.012)}.progress{height:8px;background:#17283d;border-radius:999px;overflow:hidden}.progress i{display:block;height:100%;background:linear-gradient(90deg,#2788f8,#72beff);border-radius:999px}.empty{text-align:center;padding:48px;color:var(--muted)}
.service-card{display:flex;flex-direction:column;gap:14px}.service-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.service-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px}.mini{padding:11px;border-radius:13px;background:rgba(255,255,255,.025);border:1px solid var(--line)}.mini b{display:block;margin-top:4px}.quick-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:17px}.sub-box{display:flex;gap:10px}.sub-box .input{direction:ltr;text-align:left}.network-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--ok);box-shadow:0 0 12px var(--ok);margin-left:7px}.feature-strip{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:12px}.feature{padding:18px;border-radius:18px;border:1px solid var(--line);background:rgba(12,29,47,.6)}.feature b{display:block;margin-bottom:7px}
.mobile-bar{display:none}
@media(max-width:900px){.hero{grid-template-columns:1fr}.grid,.stats{grid-template-columns:1fr 1fr}.shell{grid-template-columns:1fr}.sidebar{display:none}.quick-grid{grid-template-columns:1fr}.mobile-bar{display:flex;position:fixed;bottom:10px;right:10px;left:10px;z-index:50;background:rgba(8,23,38,.94);border:1px solid var(--line2);border-radius:18px;padding:7px;backdrop-filter:blur(18px);box-shadow:var(--shadow);justify-content:space-around}.mobile-bar a{font-size:11px;color:#9db3c8;padding:9px 8px;border-radius:11px}.mobile-bar a.active{color:#fff;background:rgba(60,151,246,.16)}body{padding-bottom:72px}.feature-strip{grid-template-columns:1fr}}
@media(max-width:580px){.navlinks .hide-sm{display:none}.grid,.stats{grid-template-columns:1fr}.hero{padding-top:42px}.hero h1{font-size:43px;letter-spacing:-1px}.container{width:min(100% - 22px,1200px)}.top-title{align-items:flex-start}.top-title .btn{white-space:nowrap}.sub-box{flex-direction:column}.card{padding:18px}.service-meta{grid-template-columns:1fr 1fr}}

.admin-hero{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;padding:24px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(135deg,rgba(36,118,199,.14),rgba(13,29,48,.72));box-shadow:var(--shadow);margin:25px 0 18px;overflow:hidden;position:relative}
.admin-hero:after{content:"";position:absolute;width:240px;height:240px;border-radius:50%;background:rgba(75,165,255,.10);left:-80px;top:-120px}.admin-hero>*{position:relative;z-index:1}.admin-kicker{font-size:11px;color:#7cbcff;font-weight:900;letter-spacing:1.2px}.admin-actions{display:flex;gap:9px;flex-wrap:wrap}
.kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.kpi{padding:18px;min-height:112px;display:flex;flex-direction:column;justify-content:space-between}.kpi .label{color:var(--muted);font-size:12px}.kpi .value{font-size:26px;font-weight:900}.kpi .hint{font-size:11px;color:#67839f}
.panel-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:16px}.panel-card{padding:20px}.panel-card .panel-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}.panel-card .panel-title h3{margin:0}
.node-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.node-card{padding:18px;position:relative}.node-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.node-status{display:flex;align-items:center;gap:7px;font-weight:900}.status-dot{width:9px;height:9px;border-radius:50%;background:#8190a0}.status-dot.online{background:var(--ok);box-shadow:0 0 12px rgba(73,213,156,.65)}.status-dot.offline{background:var(--danger);box-shadow:0 0 12px rgba(255,113,133,.45)}.node-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:15px 0}.node-meta .mini{padding:10px}.node-actions{display:flex;gap:7px;flex-wrap:wrap}
.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px;flex-wrap:wrap}.toolbar .search{min-width:220px}
.form-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.switch-row{display:flex;gap:16px;flex-wrap:wrap;align-items:center;margin:10px 0}.switch-row label{display:flex;gap:7px;align-items:center;color:#b9cadb}
.catalog-product{padding:20px;margin-bottom:16px}.catalog-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.plan-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:16px}.plan-card{padding:15px;border:1px solid var(--line);background:rgba(255,255,255,.018);border-radius:16px}.plan-card .price{font-size:21px;margin:8px 0}
.dev-hero{display:grid;grid-template-columns:1fr .8fr;gap:16px;align-items:stretch}.dev-card{padding:22px}.codebox{direction:ltr;text-align:left;background:#030a11;border:1px solid #17314b;border-radius:14px;padding:14px;overflow:auto;color:#a8d8ff;font-family:Consolas,monospace;font-size:12px;line-height:1.8}.ability-list{display:flex;gap:8px;flex-wrap:wrap}.ability{padding:7px 9px;border:1px solid var(--line);border-radius:999px;font-size:11px;color:#9bc8ef;background:rgba(78,159,236,.06)}
.chart-bars{display:flex;align-items:end;gap:7px;height:180px;padding-top:20px}.bar-col{flex:1;display:flex;flex-direction:column;align-items:center;gap:6px;min-width:8px}.bar{width:100%;max-width:22px;border-radius:6px 6px 2px 2px;background:linear-gradient(180deg,#72beff,#2788f8);min-height:3px}.bar-label{font-size:9px;color:#5f7b95;writing-mode:vertical-rl;transform:rotate(180deg);max-height:48px;overflow:hidden}
.badge-danger{color:#ff9baa;background:rgba(255,113,133,.08);border-color:rgba(255,113,133,.18)}.badge-warn{color:#ffd889;background:rgba(255,201,102,.08);border-color:rgba(255,201,102,.17)}
@media(max-width:1050px){.kpi-grid{grid-template-columns:repeat(2,1fr)}.panel-grid,.dev-hero{grid-template-columns:1fr}.node-grid{grid-template-columns:1fr}.plan-grid{grid-template-columns:1fr 1fr}.form-grid{grid-template-columns:1fr 1fr}}
@media(max-width:620px){.kpi-grid,.form-grid,.plan-grid{grid-template-columns:1fr}.admin-hero{align-items:flex-start;flex-direction:column}.node-meta{grid-template-columns:1fr 1fr}}

.landing-nav{display:flex;align-items:center;gap:5px}.landing-nav a{padding:9px 11px;color:#9fb4c9;font-size:13px;font-weight:700;border-radius:10px}.landing-nav a:hover{color:#fff;background:rgba(255,255,255,.04)}
.hero-service{padding:64px 0 34px}.hero-service .hero{padding:0}.trust-row{display:flex;gap:9px;flex-wrap:wrap;margin-top:22px}.trust-chip{display:flex;align-items:center;gap:7px;padding:9px 11px;border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.018);font-size:12px;color:#b7cada}
.network-console{padding:22px}.console-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:15px}.console-map{padding:19px 0;display:grid;gap:10px}.route-line{display:grid;grid-template-columns:90px 1fr auto;gap:10px;align-items:center;padding:11px;border-radius:13px;background:rgba(255,255,255,.022);border:1px solid var(--line)}.route-track{height:5px;background:#172c42;border-radius:999px;overflow:hidden}.route-track i{display:block;height:100%;background:linear-gradient(90deg,#2788f8,#75c2ff);border-radius:999px}
.selector{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.selector-card{padding:18px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(180deg,rgba(15,34,54,.7),rgba(9,23,39,.75));position:relative;overflow:hidden}.selector-card.recommended{border-color:rgba(78,167,255,.42);box-shadow:0 12px 40px rgba(33,125,224,.11)}.selector-card.recommended:before{content:"پیشنهاد BlueGate";position:absolute;left:12px;top:12px;font-size:9px;font-weight:900;color:#06111e;background:#74c0ff;padding:5px 7px;border-radius:999px}.selector-icon{font-size:25px;margin-bottom:12px}.selector-card h3{margin:0 0 7px}.selector-card p{color:var(--muted);font-size:12px;line-height:1.8;min-height:64px}.fit-list{display:grid;gap:7px;margin:13px 0}.fit{font-size:11px;color:#b8cada;display:flex;gap:7px;align-items:center}.fit:before{content:"✓";color:var(--ok);font-weight:900}
.compare-wrap{overflow:auto}.compare{width:100%;border-collapse:separate;border-spacing:0}.compare th,.compare td{padding:15px;border-bottom:1px solid var(--line);text-align:center;min-width:130px}.compare th:first-child,.compare td:first-child{text-align:right;color:var(--muted);position:sticky;right:0;background:#0c1e31;z-index:1}.compare th{color:#fff}.compare .best{background:rgba(55,148,243,.055)}
.scenario-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.scenario{padding:20px}.scenario .num{font-size:10px;color:#6eb8fa;font-weight:900;letter-spacing:1px}.scenario h3{margin:8px 0}.scenario p{color:var(--muted);line-height:1.85;font-size:13px}
.emergency-banner{display:grid;grid-template-columns:1.1fr .9fr;gap:18px;padding:26px;background:linear-gradient(120deg,rgba(63,34,100,.32),rgba(12,32,52,.92));border:1px solid rgba(145,100,230,.2);border-radius:24px;box-shadow:var(--shadow)}.emergency-steps{display:grid;gap:8px}.emergency-step{padding:12px;border-radius:13px;background:rgba(255,255,255,.025);border:1px solid var(--line)}
.product-band{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:24px;border-radius:22px;border:1px solid var(--line);background:rgba(12,29,47,.7)}.product-band h3{margin:0 0 7px}.support-band{display:grid;grid-template-columns:1fr auto;align-items:center;gap:20px;padding:27px;border-radius:24px;background:linear-gradient(135deg,rgba(30,106,181,.2),rgba(12,29,47,.8));border:1px solid rgba(78,166,255,.22)}
.faq{display:grid;gap:9px}.faq details{border:1px solid var(--line);background:rgba(12,29,47,.65);border-radius:15px;padding:15px 17px}.faq summary{cursor:pointer;font-weight:900}.faq p{color:var(--muted);line-height:1.9}
@media(max-width:950px){.landing-nav{display:none}.selector{grid-template-columns:1fr 1fr}.scenario-grid{grid-template-columns:1fr}.emergency-banner{grid-template-columns:1fr}}
@media(max-width:580px){.selector{grid-template-columns:1fr}.product-band,.support-band{align-items:flex-start;flex-direction:column;display:flex}.hero-service{padding-top:32px}.route-line{grid-template-columns:75px 1fr auto}}
</style>@stack('head')
</head>
<body>
<header class="container"><nav class="nav">
<a class="brand" href="/"><i class="brand-mark"></i><span>Blue</span>Gate</a>
<div class="landing-nav hide-sm"><a href="/#services">سرویس‌ها</a><a href="/#compare">مقایسه</a><a href="/#faq">سوالات</a></div>
<div class="navlinks">@auth<a class="btn ghost hide-sm" href="{{ route('app.dashboard') }}">داشبورد</a>
<form method="post" action="{{ route('logout') }}">@csrf<button class="btn" type="submit">خروج</button></form>
@else<a class="btn ghost" href="{{ route('login') }}">ورود</a><a class="btn primary" href="{{ route('register') }}">ساخت حساب</a>@endauth</div>
</nav></header>
@yield('body')
<footer class="footer">BlueGate V4 · Secure Network Platform</footer>
@stack('scripts')</body></html>